version: '3'
services: 
    web:
        image: node:alpine
        stdin_open: true
        container_name: web
        volumes: 
            - ./:/app
        working_dir: /app
        command: npm install
        command: npm run start
        ports:
            - "3000:3000"   